apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: spark
  labels:
    app: spark-history-server
spec:
  type: NodePort
  ports:
  - port: 18080
    targetPort: 18080
    nodePort: 30180
    name: history-server
  selector:
    app: spark-history-server 