apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      serviceAccountName: spark-service-account
      containers:
      - name: spark-history-server
        image: spark-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 18080
          name: history-server
        env:
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_HOST
          value: "spark-master"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        volumeMounts:
        - name: spark-config
          mountPath: /opt/spark/conf
        - name: spark-logs
          mountPath: /opt/spark/spark-events
        - name: scripts
          mountPath: /opt/spark/scripts
        - name: data
          mountPath: /opt/spark/data
        command: ["./entrypoint.sh"]
        args: ["history"]
        livenessProbe:
          httpGet:
            path: /
            port: 18080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
      - name: spark-logs
        persistentVolumeClaim:
          claimName: spark-logs-pvc
      - name: scripts
        hostPath:
          path: /Users/youyue/Documents/Study/DataEng/Spark/scripts
          type: Directory
      - name: data
        hostPath:
          path: /Users/youyue/Documents/Study/DataEng/Spark/data
          type: Directory
